version: '3.4'

services:
    app:
        image: "node:alpine"
        working_dir: /app
        volumes:
            - ./:/app
        expose:
            - "3000"
        command: "npm start"
        ports:
            - "3003:3000"

